import { StyleSheet } from "react-native";

export const homeStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f9f5fd",
  },
  container: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 15,
    paddingBottom: 20,
    backgroundColor: "#f9f5fd",
  },
  header: {
    fontSize: 28,
    fontWeight: "700",
    color: "#6c63ff",
    marginBottom: 15,
    textAlign: "center",
    marginTop: 0,
  },
  promptBox: {
    backgroundColor: "#fff",
    padding: 20,
    borderRadius: 16,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
    marginBottom: 30,
  },
  promptText: {
    fontSize: 22,
    fontWeight: "700",
    color: "#333",
    marginBottom: 15,
    textAlign: "center",
  },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 12,
    padding: 12,
    backgroundColor: "#fafafa",
    minHeight: 80,
    marginBottom: 10,
    fontSize: 16,
    textAlignVertical: "top",
  },
  submitButton: {
    backgroundColor: "#6c63ff",
    paddingVertical: 12,
    borderRadius: 10,
    shadowColor: "#6c63ff",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  submitButtonText: {
    color: "#fff",
    textAlign: "center",
    fontWeight: "600",
    fontSize: 16,
  },
  submittedIndicator: {
    backgroundColor: "#e8f5e9",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 10,
    alignItems: "center",
  },
  submittedText: {
    color: "#2e7d32",
    fontWeight: "600",
    fontSize: 14,
  },
  section: {
    marginBottom: 30,
  },
  sectionHeader: {
    fontSize: 22,
    fontWeight: "700",
    marginBottom: 15,
    color: "#333",
  },
  contentWrapper: {
    position: "relative",
  },
  blurredSection: {
    position: "relative",
  },
  lockedContent: {
    opacity: 0.3,
  },
  blurOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
    overflow: "hidden",
  },
  lockMessage: {
    alignItems: "center",
    padding: 20,
  },
  lockIcon: {
    fontSize: 48,
    marginBottom: 10,
  },
  lockText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    textAlign: "center",
  },
  replyBox: {
    backgroundColor: "#f0ebff",
    padding: 12,
    borderRadius: 10,
    marginBottom: 8,
  },
  friendName: {
    fontWeight: "bold",
    color: "#6c63ff",
    marginBottom: 4,
  },
  friendReply: {
    color: "#333",
    fontSize: 14,
  },
  pastBox: {
    backgroundColor: "#fff",
    padding: 15,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  pastPrompt: {
    fontWeight: "600",
    color: "#444",
    marginBottom: 10,
    fontSize: 16,
  },
  yourReplyBox: {
    backgroundColor: "#f0ebff",
    padding: 10,
    borderRadius: 8,
    marginBottom: 10,
  },
  yourReplyLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#6c63ff",
    marginBottom: 4,
  },
  pastReply: {
    color: "#333",
    fontSize: 14,
  },
  pastFriendsReplies: {
    marginTop: 10,
  },
  pastReplyBox: {
    backgroundColor: "#fafafa",
    padding: 8,
    borderRadius: 6,
    marginBottom: 6,
    flexDirection: "row",
    flexWrap: "wrap",
  },
  pastFriendName: {
    fontWeight: "600",
    color: "#6c63ff",
    marginRight: 5,
    fontSize: 13,
  },
  pastFriendReply: {
    color: "#555",
    fontSize: 13,
    flex: 1,
  },
});
