import { StyleSheet } from "react-native";

// VARIANT 1: Original Purple Theme (Current)
export const purpleTheme = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f9f5fd",
  },
  container: {
    flexGrow: 1,
    backgroundColor: "#f9f5fd",
  },
  promptContainerFull: {
    minHeight: "100%",
    paddingHorizontal: 20,
    paddingTop: 40,
    paddingBottom: 40,
    justifyContent: "center",
  },
  promptContainerNormal: {
    paddingHorizontal: 20,
    paddingTop: 40,
    paddingBottom: 20,
  },
  header: {
    fontSize: 38,
    fontWeight: "800",
    color: "#6c63ff",
    marginBottom: 40,
    textAlign: "center",
    letterSpacing: 0.5,
  },
  promptBox: {
    backgroundColor: "#fff",
    padding: 40,
    borderRadius: 24,
    shadowColor: "#6c63ff",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    borderWidth: 3,
    borderColor: "#f0ebff",
    justifyContent: "center",
  },
  promptText: {
    fontSize: 28,
    fontWeight: "700",
    color: "#333",
    marginBottom: 20,
    textAlign: "center",
    lineHeight: 38,
  },
  friendsWaiting: {
    fontSize: 16,
    fontWeight: "600",
    color: "#6c63ff",
    textAlign: "center",
    marginBottom: 30,
    opacity: 0.8,
  },
  input: {
    borderWidth: 2,
    borderColor: "#ddd",
    borderRadius: 16,
    padding: 16,
    backgroundColor: "#fafafa",
    minHeight: 120,
    marginBottom: 20,
    fontSize: 18,
    textAlignVertical: "top",
  },
  submitButton: {
    backgroundColor: "#6c63ff",
    paddingVertical: 16,
    borderRadius: 14,
    shadowColor: "#6c63ff",
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
  },
  submitButtonText: {
    color: "#fff",
    textAlign: "center",
    fontWeight: "700",
    fontSize: 18,
  },
  submittedIndicator: {
    backgroundColor: "#e8f5e9",
    paddingVertical: 10,
    paddingHorizontal: 15,
    borderRadius: 10,
    alignItems: "center",
  },
  submittedText: {
    color: "#2e7d32",
    fontWeight: "600",
    fontSize: 14,
  },
  section: {
    marginBottom: 40,
    marginTop: 20,
    paddingHorizontal: 20,
  },
  sectionHeader: {
    fontSize: 24,
    fontWeight: "700",
    marginBottom: 15,
    color: "#333",
  },
  contentWrapper: {
    position: "relative",
  },
  blurredSection: {
    position: "relative",
  },
  lockedContent: {
    opacity: 0.3,
  },
  blurOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: 12,
    overflow: "hidden",
  },
  lockMessage: {
    alignItems: "center",
    padding: 20,
  },
  lockIcon: {
    fontSize: 48,
    marginBottom: 10,
  },
  lockText: {
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
    textAlign: "center",
  },
  replyBox: {
    backgroundColor: "#f0ebff",
    padding: 12,
    borderRadius: 10,
    marginBottom: 8,
  },
  friendName: {
    fontWeight: "bold",
    color: "#6c63ff",
    marginBottom: 4,
  },
  friendReply: {
    color: "#333",
    fontSize: 14,
  },
  pastBox: {
    backgroundColor: "#fff",
    padding: 15,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  pastDate: {
    fontSize: 12,
    fontWeight: "600",
    color: "#999",
    marginBottom: 8,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  pastPrompt: {
    fontWeight: "600",
    color: "#444",
    marginBottom: 10,
    fontSize: 16,
  },
  yourReplyBox: {
    backgroundColor: "#f0ebff",
    padding: 10,
    borderRadius: 8,
    marginBottom: 10,
  },
  yourReplyLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#6c63ff",
    marginBottom: 4,
  },
  pastReply: {
    color: "#333",
    fontSize: 14,
  },
  pastFriendsReplies: {
    marginTop: 10,
  },
  pastFriendsLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#666",
    marginBottom: 10,
  },
  pastReplyBox: {
    backgroundColor: "#fafafa",
    padding: 8,
    borderRadius: 6,
    marginBottom: 6,
    flexDirection: "row",
    flexWrap: "wrap",
  },
  pastReplyCard: {
    backgroundColor: "#f7f4ff",
    padding: 12,
    borderRadius: 10,
    marginBottom: 10,
  },
  pastReplyHeader: {
    marginBottom: 6,
  },
  pastFriendName: {
    fontWeight: "600",
    color: "#6c63ff",
    fontSize: 14,
  },
  pastFriendReply: {
    color: "#333",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 8,
  },
  pastPromptsToggle: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 15,
    backgroundColor: "#fff",
    borderRadius: 12,
    marginBottom: 15,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  toggleIcon: {
    fontSize: 18,
    color: "#6c63ff",
    fontWeight: "600",
  },
  replyActions: {
    flexDirection: "row",
    marginTop: 10,
    gap: 15,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  actionIcon: {
    fontSize: 18,
  },
  likedIcon: {
    transform: [{ scale: 1.2 }],
  },
  actionText: {
    fontSize: 14,
    color: "#666",
    fontWeight: "500",
  },
  replyInputContainer: {
    marginTop: 12,
    backgroundColor: "#fafafa",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#e0e0e0",
  },
  replyInput: {
    borderWidth: 0,
    backgroundColor: "transparent",
    fontSize: 14,
    color: "#333",
    minHeight: 40,
    textAlignVertical: "top",
  },
  replyInputActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 10,
    marginTop: 8,
  },
  replyCancel: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 8,
  },
  replyCancelText: {
    color: "#666",
    fontSize: 14,
    fontWeight: "600",
  },
  replySend: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: "#6c63ff",
    borderRadius: 8,
  },
  replySendText: {
    color: "#fff",
    fontSize: 14,
    fontWeight: "600",
  },
  repliesContainer: {
    marginTop: 12,
    paddingLeft: 10,
    borderLeftWidth: 3,
    borderLeftColor: "#e0e0e0",
  },
  replyItem: {
    marginBottom: 8,
    backgroundColor: "#f9f9f9",
    padding: 10,
    borderRadius: 8,
  },
  replyUsername: {
    fontSize: 13,
    fontWeight: "600",
    color: "#6c63ff",
    marginBottom: 4,
  },
  replyTextDisplay: {
    fontSize: 13,
    color: "#333",
    lineHeight: 18,
  },
});

// VARIANT 2: Ocean Blue Theme
export const oceanTheme = StyleSheet.create({
  ...purpleTheme,
  safeArea: {
    flex: 1,
    backgroundColor: "#e8f4f8",
  },
  container: {
    flexGrow: 1,
    backgroundColor: "#e8f4f8",
  },
  header: {
    fontSize: 38,
    fontWeight: "800",
    color: "#0077b6",
    marginBottom: 40,
    textAlign: "center",
    letterSpacing: 0.5,
  },
  promptBox: {
    backgroundColor: "#fff",
    padding: 40,
    borderRadius: 24,
    shadowColor: "#0077b6",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    borderWidth: 3,
    borderColor: "#caf0f8",
    justifyContent: "center",
  },
  friendsWaiting: {
    fontSize: 16,
    fontWeight: "600",
    color: "#0077b6",
    textAlign: "center",
    marginBottom: 30,
    opacity: 0.8,
  },
  submitButton: {
    backgroundColor: "#0077b6",
    paddingVertical: 16,
    borderRadius: 14,
    shadowColor: "#0077b6",
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
  },
  replyBox: {
    backgroundColor: "#caf0f8",
    padding: 12,
    borderRadius: 10,
    marginBottom: 8,
  },
  friendName: {
    fontWeight: "bold",
    color: "#0077b6",
    marginBottom: 4,
  },
  yourReplyBox: {
    backgroundColor: "#caf0f8",
    padding: 10,
    borderRadius: 8,
    marginBottom: 10,
  },
  yourReplyLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#0077b6",
    marginBottom: 4,
  },
  pastReplyCard: {
    backgroundColor: "#d9f2f9",
    padding: 12,
    borderRadius: 10,
    marginBottom: 10,
  },
  pastFriendName: {
    fontWeight: "600",
    color: "#0077b6",
    fontSize: 14,
  },
  toggleIcon: {
    fontSize: 18,
    color: "#0077b6",
    fontWeight: "600",
  },
  replySend: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: "#0077b6",
    borderRadius: 8,
  },
  replyUsername: {
    fontSize: 13,
    fontWeight: "600",
    color: "#0077b6",
    marginBottom: 4,
  },
});

// VARIANT 3: Dark Mode
export const darkTheme = StyleSheet.create({
  ...purpleTheme,
  safeArea: {
    flex: 1,
    backgroundColor: "#1a1a1a",
  },
  container: {
    flexGrow: 1,
    backgroundColor: "#1a1a1a",
  },
  header: {
    fontSize: 38,
    fontWeight: "800",
    color: "#bb86fc",
    marginBottom: 40,
    textAlign: "center",
    letterSpacing: 0.5,
  },
  promptBox: {
    backgroundColor: "#2d2d2d",
    padding: 40,
    borderRadius: 24,
    shadowColor: "#bb86fc",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    borderWidth: 3,
    borderColor: "#3d3d3d",
    justifyContent: "center",
  },
  promptText: {
    fontSize: 28,
    fontWeight: "700",
    color: "#ffffff",
    marginBottom: 20,
    textAlign: "center",
    lineHeight: 38,
  },
  friendsWaiting: {
    fontSize: 16,
    fontWeight: "600",
    color: "#bb86fc",
    textAlign: "center",
    marginBottom: 30,
    opacity: 0.8,
  },
  input: {
    borderWidth: 2,
    borderColor: "#3d3d3d",
    borderRadius: 16,
    padding: 16,
    backgroundColor: "#1f1f1f",
    minHeight: 120,
    marginBottom: 20,
    fontSize: 18,
    textAlignVertical: "top",
    color: "#ffffff",
  },
  submitButton: {
    backgroundColor: "#bb86fc",
    paddingVertical: 16,
    borderRadius: 14,
    shadowColor: "#bb86fc",
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
  },
  sectionHeader: {
    fontSize: 24,
    fontWeight: "700",
    marginBottom: 15,
    color: "#ffffff",
  },
  replyBox: {
    backgroundColor: "#2d2d2d",
    padding: 12,
    borderRadius: 10,
    marginBottom: 8,
  },
  friendName: {
    fontWeight: "bold",
    color: "#bb86fc",
    marginBottom: 4,
  },
  friendReply: {
    color: "#e0e0e0",
    fontSize: 14,
  },
  pastBox: {
    backgroundColor: "#2d2d2d",
    padding: 15,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  pastPrompt: {
    fontWeight: "600",
    color: "#e0e0e0",
    marginBottom: 10,
    fontSize: 16,
  },
  yourReplyBox: {
    backgroundColor: "#3d3d3d",
    padding: 10,
    borderRadius: 8,
    marginBottom: 10,
  },
  yourReplyLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#bb86fc",
    marginBottom: 4,
  },
  pastReply: {
    color: "#e0e0e0",
    fontSize: 14,
  },
  pastReplyCard: {
    backgroundColor: "#353535",
    padding: 12,
    borderRadius: 10,
    marginBottom: 10,
  },
  pastFriendName: {
    fontWeight: "600",
    color: "#bb86fc",
    fontSize: 14,
  },
  pastFriendReply: {
    color: "#e0e0e0",
    fontSize: 14,
    lineHeight: 20,
    marginBottom: 8,
  },
  pastPromptsToggle: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 15,
    backgroundColor: "#2d2d2d",
    borderRadius: 12,
    marginBottom: 15,
    shadowColor: "#000",
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  toggleIcon: {
    fontSize: 18,
    color: "#bb86fc",
    fontWeight: "600",
  },
  actionText: {
    fontSize: 14,
    color: "#aaa",
    fontWeight: "500",
  },
  replyInputContainer: {
    marginTop: 12,
    backgroundColor: "#1f1f1f",
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: "#3d3d3d",
  },
  replyInput: {
    borderWidth: 0,
    backgroundColor: "transparent",
    fontSize: 14,
    color: "#ffffff",
    minHeight: 40,
    textAlignVertical: "top",
  },
  replySend: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: "#bb86fc",
    borderRadius: 8,
  },
  replyItem: {
    marginBottom: 8,
    backgroundColor: "#2d2d2d",
    padding: 10,
    borderRadius: 8,
  },
  replyUsername: {
    fontSize: 13,
    fontWeight: "600",
    color: "#bb86fc",
    marginBottom: 4,
  },
  replyTextDisplay: {
    fontSize: 13,
    color: "#e0e0e0",
    lineHeight: 18,
  },
});

// VARIANT 4: Warm Sunset Theme
export const sunsetTheme = StyleSheet.create({
  ...purpleTheme,
  safeArea: {
    flex: 1,
    backgroundColor: "#fff5f0",
  },
  container: {
    flexGrow: 1,
    backgroundColor: "#fff5f0",
  },
  header: {
    fontSize: 38,
    fontWeight: "800",
    color: "#ff6b35",
    marginBottom: 40,
    textAlign: "center",
    letterSpacing: 0.5,
  },
  promptBox: {
    backgroundColor: "#fff",
    padding: 40,
    borderRadius: 24,
    shadowColor: "#ff6b35",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    borderWidth: 3,
    borderColor: "#ffe5db",
    justifyContent: "center",
  },
  friendsWaiting: {
    fontSize: 16,
    fontWeight: "600",
    color: "#ff6b35",
    textAlign: "center",
    marginBottom: 30,
    opacity: 0.8,
  },
  submitButton: {
    backgroundColor: "#ff6b35",
    paddingVertical: 16,
    borderRadius: 14,
    shadowColor: "#ff6b35",
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
  },
  replyBox: {
    backgroundColor: "#ffe5db",
    padding: 12,
    borderRadius: 10,
    marginBottom: 8,
  },
  friendName: {
    fontWeight: "bold",
    color: "#ff6b35",
    marginBottom: 4,
  },
  yourReplyBox: {
    backgroundColor: "#ffe5db",
    padding: 10,
    borderRadius: 8,
    marginBottom: 10,
  },
  yourReplyLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#ff6b35",
    marginBottom: 4,
  },
  pastReplyCard: {
    backgroundColor: "#fff0ea",
    padding: 12,
    borderRadius: 10,
    marginBottom: 10,
  },
  pastFriendName: {
    fontWeight: "600",
    color: "#ff6b35",
    fontSize: 14,
  },
  toggleIcon: {
    fontSize: 18,
    color: "#ff6b35",
    fontWeight: "600",
  },
  replySend: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: "#ff6b35",
    borderRadius: 8,
  },
  replyUsername: {
    fontSize: 13,
    fontWeight: "600",
    color: "#ff6b35",
    marginBottom: 4,
  },
});

// VARIANT 5: Mint Fresh Theme
export const mintTheme = StyleSheet.create({
  ...purpleTheme,
  safeArea: {
    flex: 1,
    backgroundColor: "#f0fdf4",
  },
  container: {
    flexGrow: 1,
    backgroundColor: "#f0fdf4",
  },
  header: {
    fontSize: 38,
    fontWeight: "800",
    color: "#059669",
    marginBottom: 40,
    textAlign: "center",
    letterSpacing: 0.5,
  },
  promptBox: {
    backgroundColor: "#fff",
    padding: 40,
    borderRadius: 24,
    shadowColor: "#059669",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: 16,
    borderWidth: 3,
    borderColor: "#d1fae5",
    justifyContent: "center",
  },
  friendsWaiting: {
    fontSize: 16,
    fontWeight: "600",
    color: "#059669",
    textAlign: "center",
    marginBottom: 30,
    opacity: 0.8,
  },
  submitButton: {
    backgroundColor: "#059669",
    paddingVertical: 16,
    borderRadius: 14,
    shadowColor: "#059669",
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 8,
  },
  replyBox: {
    backgroundColor: "#d1fae5",
    padding: 12,
    borderRadius: 10,
    marginBottom: 8,
  },
  friendName: {
    fontWeight: "bold",
    color: "#059669",
    marginBottom: 4,
  },
  yourReplyBox: {
    backgroundColor: "#d1fae5",
    padding: 10,
    borderRadius: 8,
    marginBottom: 10,
  },
  yourReplyLabel: {
    fontSize: 12,
    fontWeight: "600",
    color: "#059669",
    marginBottom: 4,
  },
  pastReplyCard: {
    backgroundColor: "#ecfdf5",
    padding: 12,
    borderRadius: 10,
    marginBottom: 10,
  },
  pastFriendName: {
    fontWeight: "600",
    color: "#059669",
    fontSize: 14,
  },
  toggleIcon: {
    fontSize: 18,
    color: "#059669",
    fontWeight: "600",
  },
  replySend: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    backgroundColor: "#059669",
    borderRadius: 8,
  },
  replyUsername: {
    fontSize: 13,
    fontWeight: "600",
    color: "#059669",
    marginBottom: 4,
  },
});
