import { StyleSheet } from "react-native";
import { ThemeStyles } from "../context/ThemeContext";

export const createThemedStyles = (theme: ThemeStyles) => StyleSheet.create({
  // Layout
  safeArea: {
    flex: 1,
    backgroundColor: theme.background,
  },
  container: {
    flexGrow: 1,
    backgroundColor: theme.background,
  },
  promptContainerFull: {
    minHeight: "100%",
    paddingHorizontal: theme.spacingM,
    paddingTop: theme.spacingM,
    paddingBottom: theme.spacingXL,
    justifyContent: "center",
  },
  promptContainerNormal: {
    paddingHorizontal: theme.spacingM,
    paddingTop: theme.spacingM,
    paddingBottom: theme.spacingM,
  },

  // Typography
  header: {
    fontSize: theme.fontSizeM,
    fontWeight: theme.fontWeightSemiBold,
    color: theme.text,
    marginBottom: theme.spacingM,
    textAlign: "center",
    letterSpacing: 0.3,
  },
  promptTitle: {
    fontSize: theme.fontSizeM,
    fontWeight: theme.fontWeightSemiBold,
    color: theme.text,
    marginBottom: theme.spacingM,
    textAlign: "center",
    letterSpacing: 0.3,
  },
  promptBox: {
    backgroundColor: theme.surface,
    padding: theme.promptBoxPadding,
    borderRadius: theme.radiusXL,
    shadowColor: theme.primary,
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 8 },
    shadowRadius: theme.spacingM,
    borderWidth: 2,
    borderColor: theme.primaryLight,
    justifyContent: "center",
  },
  promptText: {
    fontSize: theme.fontSizeL,
    fontWeight: theme.fontWeightSemiBold,
    color: theme.text,
    marginBottom: theme.spacingM,
    textAlign: "center",
    lineHeight: theme.fontSizeL * 1.4,
  },
  friendsWaiting: {
    fontSize: theme.fontSizeS,
    fontWeight: theme.fontWeightMedium,
    color: theme.primary,
    textAlign: "center",
    marginBottom: theme.spacingL,
    opacity: 0.8,
  },

  // Input
  input: {
    borderWidth: 2,
    borderColor: theme.border,
    borderRadius: theme.radiusL,
    padding: theme.spacingM,
    backgroundColor: theme.primaryLight,
    minHeight: theme.inputHeight,
    marginBottom: theme.spacingM,
    fontSize: theme.fontSizeS,
    textAlignVertical: "top",
    color: theme.text,
  },

  // Buttons
  submitButton: {
    backgroundColor: theme.primary,
    paddingVertical: theme.spacingM,
    borderRadius: theme.radiusM,
    shadowColor: theme.primary,
    shadowOpacity: 0.4,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: theme.spacingXS,
  },
  submitButtonText: {
    color: "#fff",
    textAlign: "center",
    fontWeight: theme.fontWeightSemiBold,
    fontSize: theme.fontSizeS,
  },
  submittedIndicator: {
    backgroundColor: "#e8f5e9",
    paddingVertical: theme.spacingS,
    paddingHorizontal: theme.cardPadding,
    borderRadius: theme.radiusS,
    alignItems: "center",
  },
  submittedText: {
    color: "#2e7d32",
    fontWeight: theme.fontWeightMedium,
    fontSize: theme.fontSizeXS,
  },

  // Sections
  section: {
    marginBottom: theme.spacingXL,
    marginTop: theme.spacingM,
    paddingHorizontal: theme.spacingM,
  },
  sectionHeader: {
    fontSize: theme.fontSizeM,
    fontWeight: theme.fontWeightSemiBold,
    marginBottom: theme.cardPadding,
    color: theme.text,
  },
  contentWrapper: {
    position: "relative",
  },

  // Reply boxes
  replyBox: {
    backgroundColor: theme.primaryLight,
    padding: theme.spacingS,
    borderRadius: theme.radiusS,
    marginBottom: theme.spacingXS,
  },
  friendName: {
    fontWeight: theme.fontWeightSemiBold,
    color: theme.primary,
    marginBottom: 4,
    fontSize: theme.fontSizeXS,
  },
  friendReply: {
    color: theme.text,
    fontSize: theme.fontSizeXS,
  },

  // Past prompts
  pastBox: {
    backgroundColor: theme.surface,
    padding: theme.cardPadding,
    borderRadius: theme.radiusM,
    marginBottom: theme.spacingS,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  pastDate: {
    fontSize: theme.fontSizeXS - 2,
    fontWeight: theme.fontWeightMedium,
    color: theme.textSecondary,
    marginBottom: theme.spacingXS,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  pastPrompt: {
    fontWeight: theme.fontWeightMedium,
    color: theme.text,
    marginBottom: theme.spacingS,
    fontSize: theme.fontSizeS,
  },
  yourReplyBox: {
    backgroundColor: theme.primaryLight,
    padding: theme.spacingS,
    borderRadius: theme.radiusXS,
    marginBottom: theme.spacingS,
  },
  yourReplyLabel: {
    fontSize: theme.fontSizeXS - 2,
    fontWeight: theme.fontWeightMedium,
    color: theme.primary,
    marginBottom: 4,
  },
  pastReply: {
    color: theme.text,
    fontSize: theme.fontSizeXS,
  },
  pastFriendsReplies: {
    marginTop: theme.spacingS,
  },
  pastFriendsLabel: {
    fontSize: theme.fontSizeXS - 1,
    fontWeight: theme.fontWeightMedium,
    color: theme.textSecondary,
    marginBottom: theme.spacingS,
  },
  pastReplyCard: {
    backgroundColor: theme.primaryLight,
    padding: theme.spacingS,
    borderRadius: theme.radiusS,
    marginBottom: theme.spacingS,
  },
  pastReplyHeader: {
    marginBottom: 6,
  },
  pastFriendName: {
    fontWeight: theme.fontWeightMedium,
    color: theme.primary,
    fontSize: theme.fontSizeXS,
  },
  pastFriendReply: {
    color: theme.text,
    fontSize: theme.fontSizeXS,
    lineHeight: theme.fontSizeXS * 1.4,
    marginBottom: theme.spacingXS,
  },
  pastPromptsToggle: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: theme.spacingS,
    paddingHorizontal: theme.cardPadding,
    backgroundColor: theme.surface,
    borderRadius: theme.radiusM,
    marginBottom: theme.cardPadding,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  toggleIcon: {
    fontSize: theme.fontSizeS,
    color: theme.primary,
    fontWeight: theme.fontWeightMedium,
  },

  // Actions
  replyActions: {
    flexDirection: "row",
    marginTop: theme.spacingS,
    gap: theme.cardPadding,
  },
  actionButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  actionIcon: {
    fontSize: theme.fontSizeS,
  },
  likedIcon: {
    transform: [{ scale: 1.2 }],
  },
  actionText: {
    fontSize: theme.fontSizeXS,
    color: theme.textSecondary,
    fontWeight: theme.fontWeightMedium,
  },

  // Reply input
  replyInputContainer: {
    marginTop: theme.spacingS,
    backgroundColor: theme.primaryLight,
    borderRadius: theme.radiusM,
    padding: theme.spacingS,
    borderWidth: 1,
    borderColor: theme.border,
  },
  replyInput: {
    borderWidth: 0,
    backgroundColor: "transparent",
    fontSize: theme.fontSizeXS,
    color: theme.text,
    minHeight: 40,
    textAlignVertical: "top",
  },
  replyInputActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: theme.spacingS,
    marginTop: theme.spacingXS,
  },
  replyCancel: {
    paddingVertical: 6,
    paddingHorizontal: theme.spacingS,
    borderRadius: theme.radiusXS,
  },
  replyCancelText: {
    color: theme.textSecondary,
    fontSize: theme.fontSizeXS,
    fontWeight: theme.fontWeightMedium,
  },
  replySend: {
    paddingVertical: 6,
    paddingHorizontal: theme.spacingS,
    backgroundColor: theme.primary,
    borderRadius: theme.radiusXS,
  },
  replySendText: {
    color: "#fff",
    fontSize: theme.fontSizeXS,
    fontWeight: theme.fontWeightMedium,
  },

  // Replies display
  repliesContainer: {
    marginTop: theme.spacingS,
    paddingLeft: theme.spacingS,
    borderLeftWidth: 3,
    borderLeftColor: theme.border,
  },
  replyItem: {
    marginBottom: theme.spacingXS,
    backgroundColor: theme.surface,
    padding: theme.spacingS,
    borderRadius: theme.radiusXS,
  },
  replyUsername: {
    fontSize: theme.fontSizeXS - 1,
    fontWeight: theme.fontWeightMedium,
    color: theme.primary,
    marginBottom: 4,
  },
  replyTextDisplay: {
    fontSize: theme.fontSizeXS - 1,
    color: theme.text,
    lineHeight: theme.fontSizeXS * 1.3,
  },

  // Locked content (not used anymore but keeping for compatibility)
  blurredSection: {
    position: "relative",
  },
  lockedContent: {
    opacity: 0.3,
  },
  blurOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: "center",
    alignItems: "center",
    borderRadius: theme.radiusM,
    overflow: "hidden",
  },
  lockMessage: {
    alignItems: "center",
    padding: theme.spacingM,
  },
  lockIcon: {
    fontSize: 48,
    marginBottom: theme.spacingS,
  },
  lockText: {
    fontSize: theme.fontSizeS,
    fontWeight: theme.fontWeightMedium,
    color: theme.text,
    textAlign: "center",
  },
  pastReplyBox: {
    backgroundColor: theme.primaryLight,
    padding: theme.spacingXS,
    borderRadius: 6,
    marginBottom: 6,
    flexDirection: "row",
    flexWrap: "wrap",
  },

  // FRIENDS SCREEN STYLES
  headerTitle: {
    fontSize: theme.fontSizeXL,
    fontWeight: theme.fontWeightSemiBold,
    color: theme.primary,
    textAlign: "center",
    marginTop: theme.spacingM,
    marginBottom: theme.spacingS,
  },
  sectionTitle: {
    fontSize: theme.fontSizeM,
    fontWeight: theme.fontWeightSemiBold,
    color: theme.text,
    marginLeft: theme.spacingM,
    marginTop: theme.spacingL,
    marginBottom: theme.spacingS,
  },
  searchContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.surface,
    borderRadius: theme.radiusL,
    margin: theme.spacingM,
    paddingHorizontal: theme.spacingM,
    paddingVertical: theme.spacingS,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  searchIcon: {
    marginRight: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: theme.fontSizeS,
    color: theme.text,
  },
  userCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: theme.surface,
    padding: theme.spacingM,
    borderRadius: theme.radiusL,
    marginBottom: theme.spacingS,
    marginHorizontal: theme.spacingM,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  avatar: {
    width: 55,
    height: 55,
    borderRadius: 27.5,
    marginRight: theme.spacingS,
    borderWidth: 2,
    borderColor: theme.primaryLight,
  },
  userInfo: {
    flex: 1,
  },
  userName: {
    fontSize: theme.fontSizeS,
    fontWeight: theme.fontWeightSemiBold,
    color: theme.text,
    marginBottom: 3,
  },
  userHandle: {
    fontSize: theme.fontSizeXS - 1,
    color: theme.textSecondary,
    marginBottom: 3,
  },
  mutualFriends: {
    fontSize: theme.fontSizeXS - 2,
    color: theme.primary,
    fontWeight: theme.fontWeightMedium,
  },
  followButton: {
    backgroundColor: theme.primary,
    paddingHorizontal: theme.spacingM + 4,
    paddingVertical: theme.spacingS - 2,
    borderRadius: theme.radiusS,
    shadowColor: theme.primary,
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  followButtonText: {
    color: "#fff",
    fontSize: theme.fontSizeXS,
    fontWeight: theme.fontWeightSemiBold,
  },
  followingButton: {
    backgroundColor: theme.primaryLight,
    borderWidth: 0,
    shadowOpacity: 0,
  },
  followingButtonText: {
    color: theme.primary,
  },
  actionButtons: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  removeButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: theme.primaryLight,
    justifyContent: "center",
    alignItems: "center",
  },
  noResultsContainer: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: theme.spacingXL * 2,
    paddingHorizontal: theme.spacingM,
  },
  noResultsText: {
    fontSize: theme.fontSizeM,
    fontWeight: theme.fontWeightSemiBold,
    color: theme.text,
    marginTop: theme.spacingM,
    marginBottom: theme.spacingXS,
  },
  noResultsSubtext: {
    fontSize: theme.fontSizeS,
    color: theme.textSecondary,
    textAlign: "center",
  },

  // PROFILE SCREEN STYLES
  header: {
    width: "100%",
    height: 160,
    justifyContent: "center",
    alignItems: "center",
    borderBottomLeftRadius: theme.radiusL + 9,
    borderBottomRightRadius: theme.radiusL + 9,
    marginBottom: 60,
    marginTop: 0,
    overflow: "visible",
  },
  profileImageContainer: {
    alignItems: "center",
    marginTop: -90,
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 4,
    borderColor: "#fff",
    marginBottom: theme.spacingM,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 6,
  },
  placeholder: {
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: theme.border,
  },
  displayName: {
    fontSize: theme.fontSizeL,
    fontWeight: theme.fontWeightBold,
    color: theme.text,
    marginTop: theme.spacingS,
    marginBottom: 3,
    textAlign: "center",
  },
  username: {
    fontSize: theme.fontSizeS,
    color: theme.textSecondary,
    marginBottom: theme.spacingM,
    textAlign: "center",
  },
  bio: {
    fontSize: theme.fontSizeS,
    color: theme.text,
    textAlign: "center",
    marginHorizontal: theme.spacingM + 4,
    marginBottom: theme.spacingM + 4,
  },
  displayNameInput: {
    width: "90%",
    padding: theme.spacingS,
    marginBottom: theme.spacingM,
    borderRadius: theme.radiusL,
    backgroundColor: theme.primaryLight,
    borderWidth: 1,
    borderColor: theme.border,
    alignSelf: "center",
    fontSize: theme.fontSizeS,
    color: theme.text,
    minHeight: 50,
  },
  emailBox: {
    width: "90%",
    padding: theme.spacingS - 2,
    marginBottom: theme.spacingM,
    borderRadius: theme.radiusXS,
    backgroundColor: theme.primaryLight,
    borderWidth: 1,
    borderColor: theme.border,
    alignSelf: "center",
  },
  emailLabel: {
    fontWeight: theme.fontWeightSemiBold,
    marginBottom: 5,
    color: theme.text,
  },
  emailValue: {
    color: theme.text,
  },
  button: {
    backgroundColor: theme.primary,
    paddingVertical: theme.spacingS,
    paddingHorizontal: theme.spacingL + 1,
    borderRadius: theme.radiusM + 8,
    marginTop: theme.spacingS - 2,
    shadowColor: theme.primary,
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    alignSelf: "center",
  },
  buttonText: {
    color: "#fff",
    fontWeight: theme.fontWeightSemiBold,
    fontSize: theme.fontSizeS,
    textAlign: "center",
  },
  profileImageContainerOther: {
    position: "absolute",
    bottom: -60,
    alignSelf: "center",
  },
  streakBadge: {
    position: "absolute",
    top: 10,
    right: 10,
    backgroundColor: "rgba(255, 255, 255, 0.95)",
    paddingHorizontal: theme.spacingS,
    paddingVertical: 6,
    borderRadius: theme.radiusM + 8,
    flexDirection: "row",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  streakNumber: {
    fontSize: theme.fontSizeS,
    fontWeight: theme.fontWeightBold,
    color: "#FF6B35",
    marginLeft: 4,
    marginRight: 2,
  },
  streakLabel: {
    fontSize: theme.fontSizeXS - 4,
    color: "#666",
    fontWeight: theme.fontWeightSemiBold,
  },
  customPromptContainer: {
    width: "90%",
    backgroundColor: theme.surface,
    borderRadius: theme.radiusL,
    padding: theme.spacingM + 4,
    marginTop: theme.spacingM + 4,
    marginBottom: theme.spacingM + 4,
    marginHorizontal: "5%",
    alignSelf: "center",
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  promptHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: theme.spacingS - 2,
  },
  customPromptTitle: {
    fontSize: theme.fontSizeS,
    fontWeight: theme.fontWeightBold,
    color: theme.primary,
    marginLeft: theme.spacingXS,
  },
  customPromptText: {
    fontSize: theme.fontSizeS,
    color: theme.text,
    marginBottom: theme.spacingM,
    lineHeight: theme.fontSizeS * 1.4,
  },
  promptInput: {
    borderWidth: 1,
    borderColor: theme.border,
    borderRadius: theme.radiusS,
    padding: theme.spacingS,
    backgroundColor: theme.primaryLight,
    minHeight: 80,
    marginBottom: theme.spacingS - 2,
    fontSize: theme.fontSizeXS + 1,
    textAlignVertical: "top",
    color: theme.text,
  },
  promptSubmitButton: {
    backgroundColor: theme.primary,
    paddingVertical: theme.spacingS,
    borderRadius: theme.radiusS,
    shadowColor: theme.primary,
    shadowOpacity: 0.3,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  promptSubmitText: {
    color: "#fff",
    textAlign: "center",
    fontWeight: theme.fontWeightSemiBold,
    fontSize: theme.fontSizeXS + 1,
  },
  responseSubmitted: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: theme.spacingM,
    backgroundColor: "#e8f5e9",
    borderRadius: theme.radiusS,
  },
  responseSubmittedText: {
    color: "#2e7d32",
    fontWeight: theme.fontWeightSemiBold,
    fontSize: theme.fontSizeXS + 1,
    marginLeft: theme.spacingXS,
  },
  pinnedSection: {
    width: "90%",
    marginBottom: theme.spacingXL - 10,
    alignSelf: "center",
  },
  pinnedHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: theme.spacingM,
  },
  pinnedTitle: {
    fontSize: theme.fontSizeM,
    fontWeight: theme.fontWeightBold,
    color: theme.text,
    marginLeft: theme.spacingXS,
  },
  pinnedCard: {
    backgroundColor: theme.surface,
    borderRadius: theme.radiusL,
    padding: theme.spacingM,
    marginBottom: theme.spacingS,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  pinnedPromptHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: theme.spacingXS,
  },
  pinnedPrompt: {
    fontSize: theme.fontSizeXS + 1,
    fontWeight: theme.fontWeightSemiBold,
    color: theme.text,
    flex: 1,
    marginRight: theme.spacingS - 2,
  },
  pinnedAnswer: {
    fontSize: theme.fontSizeXS + 1,
    color: theme.text,
    lineHeight: theme.fontSizeXS * 1.5,
    marginBottom: theme.spacingS,
  },
  pinnedFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  likesContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  likesText: {
    fontSize: theme.fontSizeXS - 1,
    color: theme.textSecondary,
    marginLeft: 5,
    fontWeight: theme.fontWeightMedium,
  },
  dateText: {
    fontSize: theme.fontSizeXS - 2,
    color: theme.textSecondary,
  },
  promptHelpText: {
    fontSize: theme.fontSizeXS - 1,
    color: theme.textSecondary,
    marginBottom: theme.spacingS - 2,
    lineHeight: theme.fontSizeXS * 1.3,
  },
  pinnedHelpText: {
    fontSize: theme.fontSizeXS - 1,
    color: theme.textSecondary,
    marginBottom: theme.spacingM,
    lineHeight: theme.fontSizeXS * 1.3,
  },
  emptyPinnedState: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: theme.spacingXL,
    backgroundColor: theme.primaryLight,
    borderRadius: theme.radiusS,
    borderWidth: 2,
    borderColor: theme.border,
    borderStyle: "dashed",
  },
  emptyPinnedText: {
    fontSize: theme.fontSizeS,
    fontWeight: theme.fontWeightSemiBold,
    color: theme.textSecondary,
    marginTop: theme.spacingS - 2,
  },
  emptyPinnedSubtext: {
    fontSize: theme.fontSizeXS - 1,
    color: theme.textSecondary,
    marginTop: 5,
    textAlign: "center",
    paddingHorizontal: theme.spacingM + 4,
  },
  editButton: {
    position: "absolute",
    top: 10,
    left: 10,
    backgroundColor: "rgba(0,0,0,0.3)",
    borderRadius: theme.radiusM + 8,
    padding: theme.spacingXS,
  },
  backButton: {
    position: "absolute",
    top: 10,
    left: 10,
    backgroundColor: "rgba(0,0,0,0.3)",
    borderRadius: theme.radiusM + 8,
    padding: theme.spacingXS + 2,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  colorPickerButton: {
    position: "absolute",
    top: 60,
    right: 10,
    backgroundColor: "rgba(0,0,0,0.3)",
    borderRadius: theme.radiusM + 8,
    padding: theme.spacingXS + 2,
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  colorPickerOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.7)",
    justifyContent: "center",
    alignItems: "center",
  },
  colorPickerModal: {
    backgroundColor: theme.surface,
    borderRadius: theme.radiusXL,
    padding: theme.spacingL,
    width: "85%",
    maxWidth: 400,
  },
  colorPickerTitle: {
    fontSize: theme.fontSizeL,
    fontWeight: theme.fontWeightBold,
    color: theme.text,
    marginBottom: theme.spacingM,
    textAlign: "center",
  },
  colorGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "center",
    gap: theme.spacingS,
    marginBottom: theme.spacingM,
  },
  colorOption: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  selectedColorOption: {
    borderWidth: 3,
    borderColor: "#fff",
    shadowOpacity: 0.4,
    shadowRadius: 6,
  },
  colorPickerCloseButton: {
    backgroundColor: theme.primaryLight,
    paddingVertical: theme.spacingS,
    borderRadius: theme.radiusM,
    alignItems: "center",
  },
  colorPickerCloseText: {
    color: theme.text,
    fontSize: theme.fontSizeS,
    fontWeight: theme.fontWeightSemiBold,
  },

  // Prompt header (shown after responding)
  promptHeaderContainer: {
    paddingHorizontal: theme.spacingM,
    paddingVertical: theme.spacingM,
    marginBottom: theme.spacingS,
  },
  promptHeaderText: {
    fontSize: theme.fontSizeL,
    fontWeight: theme.fontWeightBold,
    color: theme.text,
    textAlign: "center",
    lineHeight: theme.fontSizeL * 1.3,
  },

  // Past Prompts Link
  pastPromptsLink: {
    marginHorizontal: theme.spacingM,
    marginVertical: theme.spacingL,
    marginBottom: theme.spacingXL,
  },
  pastPromptsLinkContent: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: theme.surface,
    padding: theme.spacingM,
    borderRadius: theme.radiusL,
    borderWidth: 1,
    borderColor: theme.border,
  },
  pastPromptsLinkText: {
    flex: 1,
    fontSize: theme.fontSizeM,
    fontWeight: theme.fontWeightSemiBold,
    color: theme.text,
    marginLeft: theme.spacingS,
  },

  // Past Prompts Screen
  pastPromptsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: theme.spacingM,
    paddingVertical: theme.spacingM,
    backgroundColor: theme.surface,
    borderBottomWidth: 1,
    borderBottomColor: theme.border,
  },
  pastPromptsBackButton: {
    width: 40,
    height: 40,
    justifyContent: "center",
    alignItems: "center",
  },
  pastPromptsHeaderTitle: {
    fontSize: theme.fontSizeL,
    fontWeight: theme.fontWeightBold,
    color: theme.text,
    flex: 1,
    textAlign: "center",
    marginHorizontal: theme.spacingS,
  },
  pastPromptsContainer: {
    padding: theme.spacingM,
  },
  pastPromptCard: {
    backgroundColor: theme.surface,
    borderRadius: theme.radiusL,
    padding: theme.spacingM,
    marginBottom: theme.spacingM,
    borderWidth: 1,
    borderColor: theme.border,
  },
  pastPromptDate: {
    fontSize: theme.fontSizeXS,
    color: theme.textSecondary,
    marginBottom: theme.spacingXS,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  pastPromptQuestion: {
    fontSize: theme.fontSizeL,
    fontWeight: theme.fontWeightBold,
    color: theme.text,
    marginBottom: theme.spacingM,
    lineHeight: theme.fontSizeL * 1.3,
  },
  pastPromptYourResponse: {
    backgroundColor: theme.primaryLight,
    padding: theme.spacingS,
    borderRadius: theme.radiusM,
    marginBottom: theme.spacingM,
    borderLeftWidth: 3,
    borderLeftColor: theme.primary,
  },
  pastPromptYourLabel: {
    fontSize: theme.fontSizeXS,
    color: theme.primary,
    fontWeight: theme.fontWeightSemiBold,
    marginBottom: 4,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  pastPromptYourText: {
    fontSize: theme.fontSizeS,
    color: theme.text,
    lineHeight: theme.fontSizeS * 1.4,
  },
  pastPromptFriendsHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: theme.spacingS,
  },
  pastPromptFriendsCount: {
    fontSize: theme.fontSizeXS,
    color: theme.textSecondary,
    marginLeft: 6,
    fontWeight: theme.fontWeightMedium,
  },
  pastPromptFriendsList: {
    gap: theme.spacingS,
  },
  pastPromptFriendCard: {
    backgroundColor: theme.primaryLight,
    padding: theme.spacingS,
    borderRadius: theme.radiusM,
    borderWidth: 1,
    borderColor: theme.border,
  },
  pastPromptFriendName: {
    fontSize: theme.fontSizeXS,
    color: theme.primary,
    fontWeight: theme.fontWeightSemiBold,
    marginBottom: 4,
  },
  pastPromptFriendReply: {
    fontSize: theme.fontSizeS,
    color: theme.text,
    lineHeight: theme.fontSizeS * 1.4,
    marginBottom: theme.spacingXS,
  },
  pastPromptLikeButton: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "flex-start",
    marginTop: 4,
  },
  pastPromptLikeCount: {
    fontSize: theme.fontSizeXS,
    color: theme.textSecondary,
    marginLeft: 4,
    fontWeight: theme.fontWeightMedium,
  },
});
